import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openModel, initialBody } from './model.mjs';
import { fromMarkdown, toMarkdown } from '@opral/zettel-markdown';
import { validateDocument } from '@opral/zettel-ast';
const dir = await mkdtemp(join(tmpdir(), 'zettel-comments-current-'));
const checks = [];
let model;
try {
  model = await openModel({ path: join(dir, 'test.lix') });
  const body = initialBody();
  for (const conversationId of ['checkpoint', 'paragraph', 'csv']) await model.create({ conversationId, body });
  const before = await model.state();
  assert.equal(before.comments.length, 3);
  assert(before.comments.every(c => validateDocument(c.body).ok));
  const checkpoint = before.conversations.find(c => c.id === 'checkpoint');
  const commits = await model.query('SELECT id FROM lix_commit WHERE is_checkpoint = true');
  assert((await Promise.all(commits.map(c => model.ref('lix_commit', c.id)))).map(String).includes(checkpoint.target));
  assert.equal(before.conversations.find(c => c.id === 'paragraph').target, String(await model.ref('demo_markdown_paragraph', 'paragraph-1')));
  assert.equal(before.conversations.find(c => c.id === 'csv').target, String(await model.ref('demo_csv_row', 'row-1')));
  checks.push('All three conversations address real commit/paragraph/CSV rows through Lix row refs');
  await assert.rejects(model.create({ conversationId: 'missing', body }));
  await assert.rejects(model.create({ conversationId: 'checkpoint', authorId: 'missing', body }));
  await assert.rejects(model.create({ conversationId: 'checkpoint', body: { blocks: [] } }));
  assert.equal((await model.state()).comments.length, 3);
  checks.push('Normal conversation/author FKs and application body validation reject invalid writes');
  const edited = fromMarkdown('Edited **comment** with [a link](https://example.com).\n\n- first\n  - nested\n');
  await model.update(before.comments[0].id, edited);
  await model.lix.execute("UPDATE demo_markdown_paragraph SET text = 'Ship on Tuesday.', position = 5 WHERE id = 'paragraph-1'");
  await model.lix.execute('UPDATE demo_csv_row SET data = CAST($1 AS JSONB), position = 7 WHERE id = $2', [JSON.stringify({ team: 'Design', budget: 200 }), 'row-1']);
  await model.save();
  const persisted = await model.state();
  assert.deepEqual(persisted.conversations, before.conversations);
  assert.equal(String(await model.ref('demo_markdown_paragraph', 'paragraph-1')), before.conversations.find(c => c.id === 'paragraph').target);
  assert.equal(String(await model.ref('demo_csv_row', 'row-1')), before.conversations.find(c => c.id === 'csv').target);
  await model.close();
  model = await openModel({ path: join(dir, 'test.lix') });
  assert.deepEqual(await model.state(), persisted);
  assert.equal(toMarkdown(persisted.comments.find(c => c.id === before.comments[0].id).body), toMarkdown(edited));
  checks.push('Edited body, IDs, FKs and target refs survive snapshot close/reopen; targets stay stable after content/order edits');
  // Real divergent branches: one JSONB cell; no custom merger.
  await model.lix.execute('SELECT commit_id FROM lix_create_checkpoint()');
  const main = await model.lix.activeBranchId();
  const branch = await model.lix.createBranch({ name: 'concurrent-body' });
  const id = before.comments[0].id;
  const older = fromMarkdown('Older branch edit.\n\nOriginal second paragraph.');
  const newer = fromMarkdown('Original first paragraph.\n\nNewer branch edit.');
  await model.lix.switchBranch({ branchId: branch.id });
  await model.update(id, older);
  await model.lix.switchBranch({ branchId: main });
  await model.update(id, newer);
  await model.lix.mergeBranch({ sourceBranchId: branch.id });
  const merged = (await model.state()).comments.find(c => c.id === id);
  assert.deepEqual(merged.body, older);
  checks.push('Divergent same-comment JSONB edits: incoming whole body wins, with no paragraph-level merge');
  await model.lix.execute('SELECT commit_id FROM lix_create_checkpoint()');
  const independent = await model.lix.createBranch({ name: 'different-comments' });
  await model.lix.switchBranch({ branchId: independent.id });
  await model.update(before.comments[1].id, older);
  await model.lix.switchBranch({ branchId: main });
  await model.update(before.comments[2].id, newer);
  await model.lix.mergeBranch({ sourceBranchId: independent.id });
  const final = await model.state();
  assert.deepEqual(final.comments.find(c => c.id === before.comments[1].id).body, older);
  assert.deepEqual(final.comments.find(c => c.id === before.comments[2].id).body, newer);
  assert.deepEqual(final.conversations, before.conversations);
  checks.push('Different-comment branch edits both survive merging; conversation targets remain unchanged');
  await model.save();
  await model.close();
  model = await openModel({ path: join(dir, 'test.lix') });
  assert.deepEqual(await model.state(), final);
  checks.push('Merged result survives another durable close/reopen');
  const result = { passed: checks.length, checks, mergeWinner: 'incoming source body (publication order, not wall-clock edit order)', customMerger: false };
  await mkdir(new URL('./artifacts/', import.meta.url), { recursive: true });
  await writeFile(new URL('./artifacts/model-results.json', import.meta.url), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
} finally { if (model) await model.close(); await rm(dir, { recursive: true, force: true }); }
